### ISSUE TITLE
Does this conform to jsonapi.org rendering format?

### ISSUE THREAD

**Issue by simkimsia** [rsinger86/drf-flex-fields#16]
I cannot tell but does this conform to jsonapi.org specification on how to render the JSON format?

**Comment by rsinger86** [comment]
Nah, this takes the approach of transforming simpler fields - often hyperlink strings or PK ints - into complex, nested objects. Looks like JSON API instead appends the related objects in an `included` field. 

There is this [project](https://github.com/django-json-api/django-rest-framework-json-api), which offers some level of support for JSON API -- not sure about its support for dynamic embedding. 

My (small) team prefers the direct expansion approach; see [Stripe](https://stripe.com/docs/api#expanding_objects) for an example of a major API that does same. Though,  if you're working on a larger team, I can definitely see benefit of looking to a well-documented standard like JSON API, rather than trying to come up with and standardize on your own spec.

**Comment by simkimsia** [comment]
Thanks for the clarification @rsinger86 I still need to think. If you and Stripe prefer the direct expansion approach, there's must be a good reason for it.
